# Generated by Django 5.0.14 on 2026-09-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(choices=[('xbz', 'XBZ'), ('asia', 'Asia Import'), ('somarcas', 'Só Marcas'), ('spot', 'Spot Gifts')], max_length=20)),
                ('codigo_pai', models.CharField(help_text='Código do produto-pai no fornecedor (CodigoAmigavel na xbz, referencia na asia, ProdReference na spot).', max_length=64)),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('imagens', models.JSONField(blank=True, default=list)),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('descontinuado', models.BooleanField(default=False, help_text="Descarte permanente (ex.: regra do prefixo P@ da xbz). Diferente de 'estoque zero' (ver Variacao.status).")),
                ('atualizado_em_fornecedor', models.DateTimeField(blank=True, help_text='Só preenchido quando o fornecedor informa data de atualização (hoje, apenas a Spot manda isso — ver samples/RELATORIO.md).', null=True)),
                ('payload_bruto', models.JSONField(blank=True, default=dict)),
                ('hash_conteudo', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='instancias.instancia')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('nome', models.CharField(max_length=500)),
                ('ncm', models.CharField(blank=True, help_text="NCM brasileiro. Na Spot, o único campo fiscal disponível é o 'Taric', que NÃO é confirmado como equivalente ao NCM — não preencher este campo a partir do Taric sem confirmação do fornecedor (ver config.FORNECEDOR_CONFIG / pendências no README).", max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('cor', models.CharField(blank=True, max_length=100)),
                ('tamanho', models.CharField(blank=True, max_length=100)),
                ('capacidade', models.CharField(blank=True, max_length=100)),
                ('imagens', models.JSONField(blank=True, default=list)),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('payload_bruto', models.JSONField(blank=True, default=dict)),
                ('hash_conteudo', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando reposição'), ('cadastrado', 'Cadastrado no Tiny'), ('descontinuado', 'Descontinuado'), ('erro', 'Erro ao cadastrar')], default='pendente', max_length=20)),
                ('tiny_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('cadastrado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['fornecedor', 'codigo_pai'], name='catalogo_pr_fornece_bd7b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('instancia', 'fornecedor', 'codigo_pai'), name='unico_produto_por_instancia_fornecedor_codigo_pai'),
        ),
        migrations.AddIndex(
            model_name='variacao',
            index=models.Index(fields=['status'], name='catalogo_va_status_2ac098_idx'),
        ),
        migrations.AddIndex(
            model_name='variacao',
            index=models.Index(fields=['sku'], name='catalogo_va_sku_b707da_idx'),
        ),
        migrations.AddConstraint(
            model_name='variacao',
            constraint=models.UniqueConstraint(fields=('produto', 'sku'), name='unico_sku_por_produto'),
        ),
    ]
