# Generated by Django 5.0.14 on 2026-09-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='ncm',
            field=models.CharField(blank=True, help_text="NCM brasileiro. Na Spot, o único campo fiscal disponível é o 'Taric', que NÃO é confirmado como equivalente ao NCM — o normalizador da Spot (apps/fornecedores/spot.py) deixa este campo vazio e guarda o Taric em atributos, sem inventar conversão (ver pendências no README).", max_length=20),
        ),
    ]
