# Generated by Django 5.0.14 on 2026-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_variacao_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='estoque_tiny_sincronizado',
            field=models.IntegerField(blank=True, help_text='Último valor de estoque efetivamente enviado ao Tiny. Enquanto for diferente de `estoque` (ou nulo), o comando de atualização de estoque considera esta variação pendente de sincronização.', null=True),
        ),
    ]
