# Generated by Django 5.0.14 on 2026-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_variacao_estoque_tiny_sincronizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='altura',
            field=models.FloatField(blank=True, help_text='Centímetros.', null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='comprimento',
            field=models.FloatField(blank=True, help_text='Centímetros.', null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='diametro',
            field=models.FloatField(blank=True, help_text='Centímetros.', null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='largura',
            field=models.FloatField(blank=True, help_text='Centímetros.', null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='peso_bruto',
            field=models.FloatField(blank=True, help_text='Quilogramas.', null=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='peso_liquido',
            field=models.FloatField(blank=True, help_text='Quilogramas.', null=True),
        ),
    ]
