# Generated by Django 5.0.14 on 2026-09-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_variacao_altura_variacao_comprimento_and_more'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoTiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiny_id', models.BigIntegerField(help_text='Campo `id` do produto no Tiny.')),
                ('sku', models.CharField(blank=True, help_text='Campo `sku` do Tiny (o código do produto).', max_length=255)),
                ('descricao', models.CharField(blank=True, help_text='Campo `descricao` do Tiny (o nome do produto).', max_length=500)),
                ('descricao_complementar', models.TextField(blank=True, help_text='`descricaoComplementar` — só no detalhe.')),
                ('tipo', models.CharField(blank=True, help_text='`tipo`: K/S/V/F/M (kit, simples, variação, fabricado, matéria-prima).', max_length=1)),
                ('situacao', models.CharField(blank=True, help_text='`situacao`: A (ativo), I (inativo), E (excluído).', max_length=1)),
                ('tipo_variacao', models.CharField(blank=True, help_text='`tipoVariacao`: N/P/V — vem na listagem.', max_length=1)),
                ('gtin', models.CharField(blank=True, help_text='`gtin` do Tiny (GTIN/EAN); string, pode vir vazio.', max_length=20)),
                ('ncm', models.CharField(blank=True, help_text='`ncm` — só no detalhe.', max_length=20)),
                ('unidade', models.CharField(blank=True, help_text='`unidade`.', max_length=20)),
                ('origem', models.CharField(blank=True, help_text='`origem`: código 0–8 da tabela de origem — só no detalhe.', max_length=2)),
                ('marca', models.CharField(blank=True, help_text='`marca.nome` — só no detalhe.', max_length=255)),
                ('marca_id', models.BigIntegerField(blank=True, help_text='`marca.id` — só no detalhe.', null=True)),
                ('categoria', models.CharField(blank=True, help_text='`categoria.caminhoCompleto` — só no detalhe.', max_length=500)),
                ('categoria_id', models.BigIntegerField(blank=True, help_text='`categoria.id` — só no detalhe.', null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=4, help_text='`precos.preco`.', max_digits=15, null=True)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=4, help_text='`precos.precoPromocional`.', max_digits=15, null=True)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=4, help_text='`precos.precoCusto`.', max_digits=15, null=True)),
                ('largura', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('comprimento', models.FloatField(blank=True, null=True)),
                ('diametro', models.FloatField(blank=True, null=True)),
                ('peso_liquido', models.FloatField(blank=True, help_text='`dimensoes.pesoLiquido`.', null=True)),
                ('peso_bruto', models.FloatField(blank=True, help_text='`dimensoes.pesoBruto`.', null=True)),
                ('estoque_quantidade', models.FloatField(blank=True, help_text='`estoque.quantidade` — só no detalhe.', null=True)),
                ('data_criacao_tiny', models.CharField(blank=True, help_text='`dataCriacao`, string exatamente como o Tiny devolve.', max_length=40)),
                ('data_alteracao_tiny', models.CharField(blank=True, help_text='`dataAlteracao` — usado como sinal barato de mudança para pular o detalhe numa nova passada.', max_length=40)),
                ('tem_detalhe', models.BooleanField(default=False, help_text='True quando o GET /produtos/{id} já foi buscado e mesclado neste registro.')),
                ('payload_bruto', models.JSONField(blank=True, default=dict, help_text='Cru do Tiny: {"listagem": {...}, "detalhe": {...}}.')),
                ('hash_conteudo', models.CharField(blank=True, max_length=64)),
                ('sincronizado_em', models.DateTimeField(blank=True, help_text='Última vez que este item foi lido do Tiny.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_tiny', to='instancias.instancia')),
            ],
            options={
                'verbose_name': 'Produto do Tiny (espelho)',
                'verbose_name_plural': 'Produtos do Tiny (espelho)',
                'indexes': [models.Index(fields=['instancia', 'sku'], name='catalogo_pr_instanc_c4a385_idx'), models.Index(fields=['instancia', 'gtin'], name='catalogo_pr_instanc_90e3de_idx'), models.Index(fields=['instancia', 'situacao'], name='catalogo_pr_instanc_ceca74_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='produtotiny',
            constraint=models.UniqueConstraint(fields=('instancia', 'tiny_id'), name='unico_produto_tiny_por_instancia'),
        ),
    ]
