# Generated by Django 5.0.14 on 2026-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_produtotiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='preco_tiny_sincronizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Último preço de VENDA (precos.preco) efetivamente publicado no cadastro do produto no Tiny. Enquanto for diferente de `preco` (ou nulo), o comando `sincronizar_preco_tiny` considera esta variação pendente de sincronização de preço. NÃO confundir com o precoUnitario do movimento de estoque (que é custo do balanço, não preço de venda).', max_digits=10, null=True),
        ),
    ]
