# Generated by Django 5.0.14 on 2026-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_variacao_preco_tiny_sincronizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='imagens_tiny_sincronizadas',
            field=models.JSONField(blank=True, default=list, help_text='URLs de imagem que o comando `sincronizar_imagens_tiny` já confirmou estarem nos anexos do produto no Tiny. Serve de marcador para não reenviar/duplicar em reexecuções; a verificação real é sempre feita contra o GET /produtos/{id} antes de qualquer POST de anexo.'),
        ),
    ]
