/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST {email, password} -> {token, email, nome}. Público: ainda não há token. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apaga o token atual — derruba a sessão de qualquer lugar que o esteja usando. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Usado pelo frontend para popular o bloco de usuário e validar que o token ainda é válido. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/alertas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description O que precisa de atenção agora — derivado do estado atual, nada persistido. */
        get: operations["dashboard_alertas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/atividade/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description As últimas execuções de todas as instâncias. */
        get: operations["dashboard_atividade_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/resumo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Os quatro números do topo do dashboard. */
        get: operations["dashboard_resumo_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `list` (passo 8) aceita `?busca=` (nome ou cnpj), `?status=` e pagina com
         *     `InstanciaPagination`; instâncias com problema (erro, depois não
         *     conectado) vêm primeiro. Os demais actions usam o queryset simples.
         */
        get: operations["instancias_list"];
        put?: never;
        /**
         * @description `list` (passo 8) aceita `?busca=` (nome ou cnpj), `?status=` e pagina com
         *     `InstanciaPagination`; instâncias com problema (erro, depois não
         *     conectado) vêm primeiro. Os demais actions usam o queryset simples.
         */
        post: operations["instancias_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `list` (passo 8) aceita `?busca=` (nome ou cnpj), `?status=` e pagina com
         *     `InstanciaPagination`; instâncias com problema (erro, depois não
         *     conectado) vêm primeiro. Os demais actions usam o queryset simples.
         */
        get: operations["instancias_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description `list` (passo 8) aceita `?busca=` (nome ou cnpj), `?status=` e pagina com
         *     `InstanciaPagination`; instâncias com problema (erro, depois não
         *     conectado) vêm primeiro. Os demais actions usam o queryset simples.
         */
        delete: operations["instancias_destroy"];
        options?: never;
        head?: never;
        /**
         * @description `list` (passo 8) aceita `?busca=` (nome ou cnpj), `?status=` e pagina com
         *     `InstanciaPagination`; instâncias com problema (erro, depois não
         *     conectado) vêm primeiro. Os demais actions usam o queryset simples.
         */
        patch: operations["instancias_partial_update"];
        trace?: never;
    };
    "/api/instancias/{slug}/autorizar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gera um state novo e devolve a URL de autorização do Tiny para o usuário abrir. */
        get: operations["instancias_autorizar_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/{slug}/cadencias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET .../cadencias/ — lista as 4, com defaults quando ainda não configurada. */
        get: operations["instancias_cadencias_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/{slug}/cadencias/{fornecedor}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PATCH .../cadencias/<fornecedor>/ — upsert de intervalo/ativo, com a regra de mínimo da xbz. */
        patch: operations["instancias_cadencias_partial_update"];
        trace?: never;
    };
    "/api/instancias/{slug}/credenciais/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET .../credenciais/ — lista os 4 fornecedores, sempre, mesmo sem credencial configurada. */
        get: operations["instancias_credenciais_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/{slug}/credenciais/{fornecedor}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description PUT .../credenciais/<fornecedor>/ — upsert; nunca ecoa a credencial recebida. */
        put: operations["instancias_credenciais_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/{slug}/desconectar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Limpa os tokens e volta para nao_conectado. Não libera o slug (ja_foi_autorizada fica True). */
        post: operations["instancias_desconectar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instancias/{slug}/fornecedores/{fornecedor}/sincronizar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST .../fornecedores/<fornecedor>/sincronizar/ — dispara a sincronização
         *     manual (passo 10). As mesmas checagens de negócio do comando CLI
         *     (credencial ativa, limite diário da xbz) rodam aqui de forma síncrona,
         *     ANTES de criar a Execucao e enfileirar, para poder devolver um erro
         *     imediato em vez de um execucao_id que nunca vai sair de "rodando".
         */
        post: operations["instancias_fornecedores_sincronizar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiny/oauth/callback/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Recebe `code` e `state` de volta do Tiny. Sempre valida o state antes de
         *     qualquer outra coisa — ausente ou divergente é rejeitado mesmo com o
         *     slug correto — e o consome (limpa) na primeira validação, com sucesso
         *     ou não, para que não possa ser reaproveitado.
         *
         *     Única rota pública da API (passo 5: todo o resto exige token) — quem
         *     chama aqui é o navegador redirecionado pelo Tiny, sem nenhum token
         *     nosso, então a proteção real já é o state.
         *
         *     Passo 10: como quem chega aqui é o navegador (não a SPA via AJAX — o
         *     clique em "Autorizar no ERP" é uma navegação de página inteira para o
         *     Tiny), a resposta é sempre um redirect (302) de volta para o frontend,
         *     nunca JSON — não existe "retomar o wizard client-side" depois dessa
         *     navegação. Sucesso volta para a aba Fornecedores do detalhe da
         *     instância (que cumpre o papel do "passo 4" do wizard); qualquer falha
         *     (state inválido/expirado, code ausente, erro do Tiny) volta para o
         *     wizard no passo de autorização, para o usuário tentar de novo. O único
         *     caso que continua sendo JSON é o slug inexistente (404) — não é parte
         *     do fluxo normal do wizard, é uma URL malformada.
         */
        get: operations["tiny_oauth_callback_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcaoSugerida: {
            tipo: string;
            rotulo: string;
        };
        Alerta: {
            id: string;
            severidade: components["schemas"]["SeveridadeEnum"];
            tipo: string;
            instancia: components["schemas"]["InstanciaResumida"];
            fornecedor: (components["schemas"]["FornecedorEnum"] | components["schemas"]["NullEnum"]) | null;
            mensagem: string;
            /** Format: date-time */
            momento: string;
            acao_sugerida: components["schemas"]["AcaoSugerida"];
        };
        AlertasContagem: {
            abertos: number;
            requerem_acao: number;
        };
        /**
         * @description Corpo real da action `autorizar` — documentado à parte porque, sem
         *     `@extend_schema_field`/`@extend_schema`, o drf-spectacular inferia o
         *     schema de retorno a partir do `serializer_class` do ViewSet (Instancia),
         *     que não bate com o que a view de fato devolve.
         */
        AutorizarResposta: {
            /** Format: uri */
            url_autorizacao: string;
            /** Format: uri */
            redirect_uri: string;
        };
        CadenciaDetalhe: {
            fornecedor: components["schemas"]["FornecedorEnum"];
            intervalo_minutos: number;
            ativo: boolean;
            /** Format: date-time */
            proxima_execucao_em: string | null;
        };
        CadenciaFornecedor: {
            readonly fornecedor: components["schemas"]["FornecedorEnum"];
            intervalo_minutos?: number;
            ativo?: boolean;
            /** Format: date-time */
            readonly proxima_execucao_em: string | null;
        };
        /**
         * @description * `ok` - ok
         *     * `atencao` - atencao
         *     * `erro` - erro
         *     * `nao_configurado` - nao_configurado
         * @enum {string}
         */
        CorFornecedorEnum: "ok" | "atencao" | "erro" | "nao_configurado";
        /** @description Corpo do PUT .../credenciais/<fornecedor>/ — nunca ecoa o que recebeu. */
        CredencialFornecedorEntrada: {
            credenciais: {
                [key: string]: string;
            };
            /** @default true */
            ativo: boolean;
        };
        /** @description Saída de GET/PUT — nunca inclui um valor sensível completo (ver mascaramento.py). */
        CredencialFornecedorResposta: {
            fornecedor: components["schemas"]["FornecedorEnum"];
            ativo: boolean;
            configurado: boolean;
            campos_mascarados: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            criado_em: string | null;
        };
        ErrorResponse: {
            detail: string;
        };
        ExecucaoAtividade: {
            id: number;
            instancia: components["schemas"]["InstanciaResumida"];
            fornecedor: components["schemas"]["FornecedorEnum"];
            tipo: string;
            status: string;
            /** Format: date-time */
            iniciada_em: string;
            /** Format: date-time */
            finalizada_em: string | null;
            /** Format: double */
            duracao_segundos: number | null;
            total_lidos: number;
            total_novos: number;
            total_atualizados: number;
            total_cadastrados: number;
            total_ignorados: number;
            total_erros: number;
        };
        ExecucaoResumida: {
            id: number;
            fornecedor: components["schemas"]["FornecedorEnum"];
            tipo: string;
            status: string;
            /** Format: date-time */
            iniciada_em: string;
            /** Format: date-time */
            finalizada_em: string | null;
            /** Format: double */
            duracao_segundos: number | null;
            total_lidos: number;
            total_novos: number;
            total_atualizados: number;
            total_erros: number;
            mensagem_erro: string;
        };
        ExecucoesContagem: {
            total: number;
            sucesso: number;
        };
        FornecedorDetalhe: {
            fornecedor: components["schemas"]["FornecedorEnum"];
            cor: components["schemas"]["CorFornecedorEnum"];
            /** Format: date-time */
            ultima_execucao_em: string | null;
            ultima_execucao_status: (components["schemas"]["StatusExecucaoEnum"] | components["schemas"]["NullEnum"]) | null;
            produtos_total: number;
            credencial_configurada: boolean;
            credencial_ativa: boolean;
        };
        /**
         * @description * `xbz` - XBZ
         *     * `asia` - Asia Import
         *     * `somarcas` - Só Marcas
         *     * `spot` - Spot Gifts
         * @enum {string}
         */
        FornecedorEnum: "xbz" | "asia" | "somarcas" | "spot";
        /** @description Uma cor por fornecedor — ver InstanciaListagemSerializer.get_fornecedores. */
        FornecedoresStatus: {
            xbz: components["schemas"]["CorFornecedorEnum"];
            asia: components["schemas"]["CorFornecedorEnum"];
            somarcas: components["schemas"]["CorFornecedorEnum"];
            spot: components["schemas"]["CorFornecedorEnum"];
        };
        /**
         * @description Nunca inclui client_secret, access_token ou refresh_token — só
         *     indicadores (se está preenchido, quando expira, qual o status).
         */
        Instancia: {
            readonly id: number;
            nome: string;
            /** @description CNPJ do cliente, formato livre (ex.: 12.345.678/0001-90). Usado na busca da listagem de instâncias (passo 8). */
            cnpj?: string;
            /** @description Gerado automaticamente a partir do nome na criação. Fica imutável a partir do momento em que o access_token é preenchido pela primeira vez — não quando o status muda, e não volta a ser editável depois de um desconectar. */
            readonly slug: string;
            client_id?: string;
            client_secret?: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly tentativas_falha: number;
            readonly ultimo_erro: string;
            readonly access_token_preenchido: string;
            readonly refresh_token_preenchido: string;
            /**
             * Format: date-time
             * @description Quando o access_token atual foi emitido — usado para calcular a fração do tempo de vida já decorrida (renovação proativa a 70%).
             */
            readonly token_emitido_em: string | null;
            /** Format: date-time */
            readonly token_expira_em: string | null;
            /** Format: date-time */
            readonly refresh_expira_em: string | null;
            /** @description Último valor visto no header x-limit-api do Tiny (limite é por conta). */
            readonly rate_limit_por_minuto: number | null;
            /** @description Código de origem da mercadoria (tabela de origem da legislação fiscal — NF-e): 0 = nacional, 1 = estrangeira, importação direta, 2 a 8 = demais casos da tabela. Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_origem_padrao?: number | null;
            /** @description Unidade de medida padrão (ex.: UN, PC, CX). Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_unidade_medida_padrao?: string;
            readonly url_callback: string;
            /** Format: date-time */
            readonly criado_em: string;
            /** Format: date-time */
            readonly atualizado_em: string;
        };
        /**
         * @description Serializer do `retrieve` (passo 10) — só usado para 1 instância por vez,
         *     por isso faz contagens diretas em vez do aparato de Subquery/Prefetch de
         *     `listagem.py` (que existe para evitar N+1 numa lista de N linhas).
         */
        InstanciaDetalhe: {
            readonly id: number;
            nome: string;
            /** @description CNPJ do cliente, formato livre (ex.: 12.345.678/0001-90). Usado na busca da listagem de instâncias (passo 8). */
            cnpj?: string;
            /** @description Gerado automaticamente a partir do nome na criação. Fica imutável a partir do momento em que o access_token é preenchido pela primeira vez — não quando o status muda, e não volta a ser editável depois de um desconectar. */
            readonly slug: string;
            client_id?: string;
            client_secret?: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly tentativas_falha: number;
            readonly ultimo_erro: string;
            readonly access_token_preenchido: string;
            readonly refresh_token_preenchido: string;
            /**
             * Format: date-time
             * @description Quando o access_token atual foi emitido — usado para calcular a fração do tempo de vida já decorrida (renovação proativa a 70%).
             */
            readonly token_emitido_em: string | null;
            /** Format: date-time */
            readonly token_expira_em: string | null;
            /** Format: date-time */
            readonly refresh_expira_em: string | null;
            /** @description Último valor visto no header x-limit-api do Tiny (limite é por conta). */
            readonly rate_limit_por_minuto: number | null;
            /** @description Código de origem da mercadoria (tabela de origem da legislação fiscal — NF-e): 0 = nacional, 1 = estrangeira, importação direta, 2 a 8 = demais casos da tabela. Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_origem_padrao?: number | null;
            /** @description Unidade de medida padrão (ex.: UN, PC, CX). Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_unidade_medida_padrao?: string;
            readonly url_callback: string;
            /** Format: date-time */
            readonly criado_em: string;
            /** Format: date-time */
            readonly atualizado_em: string;
            readonly produtos: components["schemas"]["ProdutosDetalheContagem"];
            readonly fornecedores: components["schemas"]["FornecedorDetalhe"][];
            readonly cadencias: components["schemas"]["CadenciaDetalhe"][];
            readonly ultimas_execucoes: components["schemas"]["ExecucaoResumida"][];
        };
        /**
         * @description Serializer da listagem (passo 8): acrescenta métricas agregadas por
         *     linha. Só usado com o queryset de `apps.instancias.listagem.
         *     queryset_listagem` — os campos extras lêem anotações e o prefetch de
         *     credenciais montados lá, sem disparar consulta nova por linha.
         */
        InstanciaListagem: {
            readonly id: number;
            nome: string;
            /** @description CNPJ do cliente, formato livre (ex.: 12.345.678/0001-90). Usado na busca da listagem de instâncias (passo 8). */
            cnpj?: string;
            /** @description Gerado automaticamente a partir do nome na criação. Fica imutável a partir do momento em que o access_token é preenchido pela primeira vez — não quando o status muda, e não volta a ser editável depois de um desconectar. */
            readonly slug: string;
            client_id?: string;
            client_secret?: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly tentativas_falha: number;
            readonly ultimo_erro: string;
            readonly access_token_preenchido: string;
            readonly refresh_token_preenchido: string;
            /**
             * Format: date-time
             * @description Quando o access_token atual foi emitido — usado para calcular a fração do tempo de vida já decorrida (renovação proativa a 70%).
             */
            readonly token_emitido_em: string | null;
            /** Format: date-time */
            readonly token_expira_em: string | null;
            /** Format: date-time */
            readonly refresh_expira_em: string | null;
            /** @description Último valor visto no header x-limit-api do Tiny (limite é por conta). */
            readonly rate_limit_por_minuto: number | null;
            /** @description Código de origem da mercadoria (tabela de origem da legislação fiscal — NF-e): 0 = nacional, 1 = estrangeira, importação direta, 2 a 8 = demais casos da tabela. Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_origem_padrao?: number | null;
            /** @description Unidade de medida padrão (ex.: UN, PC, CX). Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_unidade_medida_padrao?: string;
            readonly url_callback: string;
            /** Format: date-time */
            readonly criado_em: string;
            /** Format: date-time */
            readonly atualizado_em: string;
            readonly fornecedores: components["schemas"]["FornecedoresStatus"];
            readonly produtos: components["schemas"]["ProdutosContagem"];
            readonly ultima_sincronizacao: components["schemas"]["UltimaSincronizacao"];
        };
        InstanciaResumida: {
            slug: string;
            nome: string;
        };
        InstanciasContagem: {
            ativas: number;
            total: number;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            /** Format: email */
            email: string;
            nome: string;
        };
        MeResponse: {
            /** Format: email */
            email: string;
            nome: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedInstanciaListagemList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["InstanciaListagem"][];
        };
        PatchedCadenciaFornecedor: {
            readonly fornecedor?: components["schemas"]["FornecedorEnum"];
            intervalo_minutos?: number;
            ativo?: boolean;
            /** Format: date-time */
            readonly proxima_execucao_em?: string | null;
        };
        /**
         * @description Nunca inclui client_secret, access_token ou refresh_token — só
         *     indicadores (se está preenchido, quando expira, qual o status).
         */
        PatchedInstancia: {
            readonly id?: number;
            nome?: string;
            /** @description CNPJ do cliente, formato livre (ex.: 12.345.678/0001-90). Usado na busca da listagem de instâncias (passo 8). */
            cnpj?: string;
            /** @description Gerado automaticamente a partir do nome na criação. Fica imutável a partir do momento em que o access_token é preenchido pela primeira vez — não quando o status muda, e não volta a ser editável depois de um desconectar. */
            readonly slug?: string;
            client_id?: string;
            client_secret?: string;
            readonly status?: components["schemas"]["StatusEnum"];
            readonly tentativas_falha?: number;
            readonly ultimo_erro?: string;
            readonly access_token_preenchido?: string;
            readonly refresh_token_preenchido?: string;
            /**
             * Format: date-time
             * @description Quando o access_token atual foi emitido — usado para calcular a fração do tempo de vida já decorrida (renovação proativa a 70%).
             */
            readonly token_emitido_em?: string | null;
            /** Format: date-time */
            readonly token_expira_em?: string | null;
            /** Format: date-time */
            readonly refresh_expira_em?: string | null;
            /** @description Último valor visto no header x-limit-api do Tiny (limite é por conta). */
            readonly rate_limit_por_minuto?: number | null;
            /** @description Código de origem da mercadoria (tabela de origem da legislação fiscal — NF-e): 0 = nacional, 1 = estrangeira, importação direta, 2 a 8 = demais casos da tabela. Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_origem_padrao?: number | null;
            /** @description Unidade de medida padrão (ex.: UN, PC, CX). Sem valor padrão fixo — configure antes de cadastrar produtos. */
            tiny_unidade_medida_padrao?: string;
            readonly url_callback?: string;
            /** Format: date-time */
            readonly criado_em?: string;
            /** Format: date-time */
            readonly atualizado_em?: string;
        };
        /**
         * @description * `hoje` - hoje
         *     * `7d` - 7d
         *     * `30d` - 30d
         * @enum {string}
         */
        PeriodoEnum: "hoje" | "7d" | "30d";
        ProdutosContagem: {
            total: number;
            cadastrados: number;
        };
        ProdutosDetalheContagem: {
            total: number;
            cadastrados: number;
            aguardando: number;
            com_erro: number;
        };
        ProdutosSincronizados: {
            total: number;
            periodo_anterior: number;
            diferenca: number;
        };
        Resumo: {
            periodo: components["schemas"]["PeriodoEnum"];
            instancias: components["schemas"]["InstanciasContagem"];
            produtos_sincronizados: components["schemas"]["ProdutosSincronizados"];
            execucoes_24h: components["schemas"]["ExecucoesContagem"];
            alertas: components["schemas"]["AlertasContagem"];
        };
        /**
         * @description * `critica` - critica
         *     * `atencao` - atencao
         * @enum {string}
         */
        SeveridadeEnum: "critica" | "atencao";
        SincronizarResposta: {
            execucao_id: number;
            status: components["schemas"]["StatusExecucaoEnum"];
        };
        /**
         * @description * `nao_conectado` - Não conectado
         *     * `conectado` - Conectado
         *     * `erro` - Erro
         * @enum {string}
         */
        StatusEnum: "nao_conectado" | "conectado" | "erro";
        /**
         * @description * `rodando` - Rodando
         *     * `sucesso` - Sucesso
         *     * `falha` - Falha
         *     * `parcial` - Parcial
         * @enum {string}
         */
        StatusExecucaoEnum: "rodando" | "sucesso" | "falha" | "parcial";
        UltimaSincronizacao: {
            /** Format: date-time */
            em: string | null;
            fornecedor: (components["schemas"]["FornecedorEnum"] | components["schemas"]["NullEnum"]) | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    dashboard_alertas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alerta"][];
                };
            };
        };
    };
    dashboard_atividade_list: {
        parameters: {
            query?: {
                /** @description Padrão 20, máx. 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoAtividade"][];
                };
            };
        };
    };
    dashboard_resumo_retrieve: {
        parameters: {
            query?: {
                /** @description Janela para 'produtos sincronizados'. Padrão: hoje. */
                periodo?: "30d" | "7d" | "hoje";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resumo"];
                };
            };
        };
    };
    instancias_list: {
        parameters: {
            query?: {
                /** @description Busca por nome ou CNPJ. */
                busca?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a serem retornados por página. */
                page_size?: number;
                /** @description Filtra por status exato. */
                status?: "conectado" | "erro" | "nao_conectado";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInstanciaListagemList"];
                };
            };
        };
    };
    instancias_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Instancia"];
                "application/x-www-form-urlencoded": components["schemas"]["Instancia"];
                "multipart/form-data": components["schemas"]["Instancia"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instancia"];
                };
            };
        };
    };
    instancias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanciaDetalhe"];
                };
            };
        };
    };
    instancias_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    instancias_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedInstancia"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedInstancia"];
                "multipart/form-data": components["schemas"]["PatchedInstancia"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instancia"];
                };
            };
        };
    };
    instancias_autorizar_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutorizarResposta"];
                };
            };
        };
    };
    instancias_cadencias_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadenciaFornecedor"][];
                };
            };
        };
    };
    instancias_cadencias_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fornecedor: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCadenciaFornecedor"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCadenciaFornecedor"];
                "multipart/form-data": components["schemas"]["PatchedCadenciaFornecedor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadenciaFornecedor"];
                };
            };
        };
    };
    instancias_credenciais_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredencialFornecedorResposta"][];
                };
            };
        };
    };
    instancias_credenciais_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fornecedor: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialFornecedorEntrada"];
                "application/x-www-form-urlencoded": components["schemas"]["CredencialFornecedorEntrada"];
                "multipart/form-data": components["schemas"]["CredencialFornecedorEntrada"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredencialFornecedorResposta"];
                };
            };
        };
    };
    instancias_desconectar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Instancia"];
                "application/x-www-form-urlencoded": components["schemas"]["Instancia"];
                "multipart/form-data": components["schemas"]["Instancia"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instancia"];
                };
            };
        };
    };
    instancias_fornecedores_sincronizar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fornecedor: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SincronizarResposta"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tiny_oauth_callback_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
