from django.urls import path
from rest_framework.routers import DefaultRouter

from .auth_views import LoginView, LogoutView, MeView
from .views import (
    CadastrarProdutosTinyView,
    CadastrarVariacaoTinyView,
    CadastroTinyPreviewView,
    PausarCadastroTinyView,
    RetomarCadastroTinyView,
    CadenciaFornecedorDetailView,
    CadenciasFornecedorView,
    ConfiguracoesInstanciaView,
    CredencialFornecedorDetailView,
    CredenciaisFornecedorView,
    ExecucaoDetalheView,
    ExecucaoLogsView,
    ExecucaoProdutoLogsView,
    ExecucaoProdutosView,
    ExecucoesInstanciaView,
    InstanciaViewSet,
    ProdutosEspelhoView,
    RetentarLoteExecucaoView,
    PararRetentativaLoteView,
    RetentarVariacaoExecucaoView,
    SincronizarFornecedorView,
    TinyFornecedorIdView,
    TinyOAuthCallbackView,
    VariacaoDetalheView,
)

router = DefaultRouter()
router.register("instancias", InstanciaViewSet, basename="instancia")

urlpatterns = router.urls + [
    path(
        "tiny/oauth/callback/<slug:slug>/",
        TinyOAuthCallbackView.as_view(),
        name="tiny-oauth-callback",
    ),
    path(
        "instancias/<slug:slug>/credenciais/",
        CredenciaisFornecedorView.as_view(),
        name="instancia-credenciais",
    ),
    path(
        "instancias/<slug:slug>/credenciais/<str:fornecedor>/",
        CredencialFornecedorDetailView.as_view(),
        name="instancia-credencial-detalhe",
    ),
    path(
        "instancias/<slug:slug>/configuracoes/",
        ConfiguracoesInstanciaView.as_view(),
        name="instancia-configuracoes",
    ),
    path(
        "instancias/<slug:slug>/fornecedores/<str:fornecedor>/tiny-fornecedor-id/",
        TinyFornecedorIdView.as_view(),
        name="instancia-fornecedor-tiny-id",
    ),
    path(
        "instancias/<slug:slug>/cadencias/",
        CadenciasFornecedorView.as_view(),
        name="instancia-cadencias",
    ),
    path(
        "instancias/<slug:slug>/cadencias/<str:fornecedor>/",
        CadenciaFornecedorDetailView.as_view(),
        name="instancia-cadencia-detalhe",
    ),
    path(
        "instancias/<slug:slug>/fornecedores/<str:fornecedor>/sincronizar/",
        SincronizarFornecedorView.as_view(),
        name="instancia-fornecedor-sincronizar",
    ),
    path(
        "instancias/<slug:slug>/fornecedores/<str:fornecedor>/cadastro-tiny/preview/",
        CadastroTinyPreviewView.as_view(),
        name="instancia-fornecedor-cadastro-tiny-preview",
    ),
    path(
        "instancias/<slug:slug>/fornecedores/<str:fornecedor>/cadastro-tiny/",
        CadastrarProdutosTinyView.as_view(),
        name="instancia-fornecedor-cadastro-tiny",
    ),
    path(
        "instancias/<slug:slug>/fornecedores/<str:fornecedor>/cadastro-tiny/pausar/",
        PausarCadastroTinyView.as_view(),
        name="instancia-fornecedor-cadastro-tiny-pausar",
    ),
    path(
        "instancias/<slug:slug>/fornecedores/<str:fornecedor>/cadastro-tiny/retomar/",
        RetomarCadastroTinyView.as_view(),
        name="instancia-fornecedor-cadastro-tiny-retomar",
    ),
    path(
        "instancias/<slug:slug>/produtos/",
        ProdutosEspelhoView.as_view(),
        name="instancia-produtos",
    ),
    path(
        "instancias/<slug:slug>/produtos/<int:variacao_id>/",
        VariacaoDetalheView.as_view(),
        name="instancia-produto-detalhe",
    ),
    path(
        "instancias/<slug:slug>/produtos/<int:variacao_id>/cadastro-tiny/",
        CadastrarVariacaoTinyView.as_view(),
        name="instancia-produto-cadastro-tiny",
    ),
    path(
        "instancias/<slug:slug>/execucoes/",
        ExecucoesInstanciaView.as_view(),
        name="instancia-execucoes",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/",
        ExecucaoDetalheView.as_view(),
        name="instancia-execucao-detalhe",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/logs/",
        ExecucaoLogsView.as_view(),
        name="instancia-execucao-logs",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/produtos/",
        ExecucaoProdutosView.as_view(),
        name="instancia-execucao-produtos",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/produtos/<int:variacao_id>/",
        ExecucaoProdutoLogsView.as_view(),
        name="instancia-execucao-produto-logs",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/produtos/<int:variacao_id>/retentar/",
        RetentarVariacaoExecucaoView.as_view(),
        name="instancia-execucao-produto-retentar",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/retentar-lote/",
        RetentarLoteExecucaoView.as_view(),
        name="instancia-execucao-retentar-lote",
    ),
    path(
        "instancias/<slug:slug>/execucoes/<int:execucao_id>/retentar-lote/parar/",
        PararRetentativaLoteView.as_view(),
        name="instancia-execucao-retentar-lote-parar",
    ),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
]
