# Generated by Django 5.0.14 on 2026-09-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(choices=[('xbz', 'XBZ'), ('asia', 'Asia Import'), ('somarcas', 'Só Marcas'), ('spot', 'Spot Gifts')], max_length=20)),
                ('tipo', models.CharField(choices=[('carga_inicial', 'Carga inicial'), ('incremental', 'Incremental')], max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rodando', 'Rodando'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('parcial', 'Parcial')], default='rodando', max_length=20)),
                ('total_lidos', models.PositiveIntegerField(default=0)),
                ('total_novos', models.PositiveIntegerField(default=0)),
                ('total_atualizados', models.PositiveIntegerField(default=0)),
                ('total_cadastrados', models.PositiveIntegerField(default=0)),
                ('total_ignorados', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='instancias.instancia')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('aviso', 'Aviso'), ('erro', 'Erro')], default='info', max_length=10)),
                ('mensagem', models.CharField(max_length=500)),
                ('detalhe', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sincronizacao.execucao')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='catalogo.variacao')),
            ],
            options={
                'verbose_name': 'Log de execução',
                'verbose_name_plural': 'Logs de execução',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='execucao',
            index=models.Index(fields=['instancia', 'fornecedor', '-iniciada_em'], name='sincronizac_instanc_710573_idx'),
        ),
        migrations.AddIndex(
            model_name='logitem',
            index=models.Index(fields=['execucao', 'nivel'], name='sincronizac_execuca_655159_idx'),
        ),
    ]
