# Generated by Django 5.0.14 on 2026-09-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacao', '0004_logitem_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentativaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacao_ids', models.JSONField(blank=True, default=list, help_text='variacao_id dos SKUs a retentar — snapshot resolvido no start. Fila fixa.')),
                ('selecao_todos', models.BooleanField(default=False, help_text="True = o operador pediu 'todos os erros da execução'.")),
                ('status', models.CharField(choices=[('rodando', 'Rodando'), ('concluido', 'Concluído'), ('interrompido', 'Interrompido')], default='rodando', max_length=20)),
                ('lease_token', models.CharField(blank=True, default='', max_length=36)),
                ('heartbeat_em', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processados', models.PositiveIntegerField(default=0)),
                ('sucessos', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('ignorados', models.PositiveIntegerField(default=0, help_text='SKU que já estava cadastrado quando o lote chegou nele.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retentativas_lote', to='sincronizacao.execucao')),
            ],
            options={
                'verbose_name': 'Retentativa em lote',
                'verbose_name_plural': 'Retentativas em lote',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['execucao', '-criado_em'], name='sincronizac_execuca_b45d48_idx')],
            },
        ),
    ]
