# Generated by Django 5.0.14 on 2026-09-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(choices=[('xbz', 'XBZ'), ('asia', 'Asia Import'), ('somarcas', 'Só Marcas'), ('spot', 'Spot Gifts')], max_length=20, unique=True)),
                ('url_base_imagens', models.URLField(blank=True, help_text='Usado para montar a URL de imagens quando o fornecedor devolve só o nome do arquivo (hoje: Spot). Vazio = imagem não é montada.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de fornecedor',
                'verbose_name_plural': 'Configurações de fornecedor',
            },
        ),
    ]
