# Generated by Django 5.0.14 on 2026-09-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('instancias', '0003_instancia_tiny_origem_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadenciaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(choices=[('xbz', 'XBZ'), ('asia', 'Asia Import'), ('somarcas', 'Só Marcas'), ('spot', 'Spot Gifts')], max_length=20)),
                ('intervalo_minutos', models.PositiveIntegerField(default=60)),
                ('proxima_execucao_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadencias_fornecedor', to='instancias.instancia')),
            ],
            options={
                'verbose_name': 'Cadência de sincronização',
                'verbose_name_plural': 'Cadências de sincronização',
            },
        ),
        migrations.AddConstraint(
            model_name='cadenciafornecedor',
            constraint=models.UniqueConstraint(fields=('instancia', 'fornecedor'), name='unica_cadencia_por_instancia_fornecedor'),
        ),
    ]
