# Generated by Django 5.0.14 on 2026-09-07 14:40
#
# Toda cadência de fornecedor passa a nascer DESLIGADA (ativo=False):
# nenhuma sincronização automática começa sem o usuário ativar a cadência
# pela interface. Isto só muda o DEFAULT da coluna — as linhas de
# CadenciaFornecedor que já existem no banco (com o valor que tiverem)
# NÃO são alteradas.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_cadenciafornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadenciafornecedor',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
