# Generated by Django 5.0.14 on 2026-09-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_config_spot_url_base_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadenciafornecedor',
            name='propagar_tiny',
            field=models.BooleanField(default=False),
        ),
    ]
