# Generated by Django 5.0.14 on 2026-09-04 19:15

import apps.instancias.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente a partir do nome na criação. Fica imutável assim que a instância é autorizada (conectada) pela primeira vez.', max_length=160, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', apps.instancias.fields.EncryptedTextField(blank=True)),
                ('access_token', apps.instancias.fields.EncryptedTextField(blank=True)),
                ('refresh_token', apps.instancias.fields.EncryptedTextField(blank=True)),
                ('token_expira_em', models.DateTimeField(blank=True, null=True)),
                ('refresh_expira_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nao_conectado', 'Não conectado'), ('conectado', 'Conectado'), ('erro', 'Erro')], default='nao_conectado', max_length=20)),
                ('tentativas_falha', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instância',
                'verbose_name_plural': 'Instâncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CredencialFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(choices=[('xbz', 'XBZ'), ('asia', 'Asia Import'), ('somarcas', 'Só Marcas'), ('spot', 'Spot Gifts')], max_length=20)),
                ('credenciais', apps.instancias.fields.EncryptedJSONField(blank=True, default=dict, help_text='Ex.: xbz={cnpj, token}; asia={api_key, secret_key}; somarcas={usuario, senha, estado}; spot={client_id, access_key}.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais_fornecedor', to='instancias.instancia')),
            ],
            options={
                'verbose_name': 'Credencial de fornecedor',
                'verbose_name_plural': 'Credenciais de fornecedor',
            },
        ),
        migrations.AddConstraint(
            model_name='credencialfornecedor',
            constraint=models.UniqueConstraint(fields=('instancia', 'fornecedor'), name='unico_fornecedor_por_instancia'),
        ),
    ]
