# Generated by Django 5.0.14 on 2026-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='ja_foi_autorizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instancia',
            name='oauth_state',
            field=models.CharField(blank=True, help_text='State de uso único da última URL de autorização gerada. Consumido (limpo) assim que o callback é validado, com sucesso ou não.', max_length=64),
        ),
        migrations.AddField(
            model_name='instancia',
            name='oauth_state_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='rate_limit_por_minuto',
            field=models.PositiveIntegerField(blank=True, help_text='Último valor visto no header x-limit-api do Tiny (limite é por conta).', null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='token_emitido_em',
            field=models.DateTimeField(blank=True, help_text='Quando o access_token atual foi emitido — usado para calcular a fração do tempo de vida já decorrida (renovação proativa a 70%).', null=True),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do nome na criação. Fica imutável a partir do momento em que o access_token é preenchido pela primeira vez — não quando o status muda, e não volta a ser editável depois de um desconectar.', max_length=160, unique=True),
        ),
    ]
