# Generated by Django 5.0.14 on 2026-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0002_instancia_ja_foi_autorizada_instancia_oauth_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='tiny_origem_padrao',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código de origem da mercadoria do Tiny/NF-e (0 a 8). Sem valor padrão fixo — configure antes de cadastrar produtos.', null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='tiny_unidade_medida_padrao',
            field=models.CharField(blank=True, help_text='Unidade de medida padrão (ex.: UN, PC, CX). Sem valor padrão fixo — configure antes de cadastrar produtos.', max_length=10),
        ),
    ]
