# Generated by Django 5.0.14 on 2026-09-04 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0003_instancia_tiny_origem_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='tiny_origem_padrao',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código de origem da mercadoria (tabela de origem da legislação fiscal — NF-e): 0 = nacional, 1 = estrangeira, importação direta, 2 a 8 = demais casos da tabela. Sem valor padrão fixo — configure antes de cadastrar produtos.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
