# Generated by Django 5.0.14 on 2026-09-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0004_alter_instancia_tiny_origem_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do cliente, formato livre (ex.: 12.345.678/0001-90). Usado na busca da listagem de instâncias (passo 8).', max_length=18),
        ),
    ]
