# Generated by Django 5.0.14 on 2026-09-06 20:08

import apps.instancias.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0005_instancia_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialfornecedor',
            name='credenciais',
            field=apps.instancias.fields.EncryptedJSONField(blank=True, default=dict, help_text='Ex.: xbz={cnpj, token}; asia={api_key, secret_key}; somarcas={usuario, senha, estado}; spot={access_key}.'),
        ),
    ]
