# Generated by Django 5.0.14 on 2026-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0006_alter_credencialfornecedor_credenciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialfornecedor',
            name='tiny_fornecedor_id',
            field=models.BigIntegerField(blank=True, help_text='Id do contato/fornecedor correspondente no Tiny desta instância (payload de criação de produto: fornecedores[].id). Específico por (instância, fornecedor) — nunca fixo no código. Enquanto nulo, o cadastro de novos produtos desse fornecedor no Tiny fica bloqueado.', null=True),
        ),
    ]
